[program:jobshours-reverb]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/jobshour-api/artisan reverb:start --host=127.0.0.1 --port=8080 --no-debug
numprocs=1
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/jobshours-reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=30
stopasgroup=true
killasgroup=true
startsecs=5
startretries=5
