[program:jobshours-horizon]
process_name=%(program_name)s
command=php /var/www/jobshour-api/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/jobshours-horizon.log
stopwaitsecs=3600
